/**
 * Export Menu Component
 * Provides options to share and export report data
 */

import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, Alert, Share, Platform, ActivityIndicator } from 'react-native';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import * as Clipboard from 'expo-clipboard';
import * as Print from 'expo-print';
import { useTheme } from '@/contexts/ThemeContext';

interface ExportMenuProps {
  visible: boolean;
  onClose: () => void;
  reportData: {
    period: string;
    dateRange: string;
    totalKwh: number;
    totalCost: number;
    appliances: Array<{
      name: string;
      kwh: number;
      cost: number;
    }>;
  };
}

export function ExportMenu({ visible, onClose, reportData }: ExportMenuProps) {
  const { colors, isDark } = useTheme();
  const styles = createStyles(colors);
  const [isExporting, setIsExporting] = useState(false);

  const generateTextReport = (): string => {
    const { period, dateRange, totalKwh, totalCost, appliances } = reportData;
    
    let report = `📊 Energy Consumption Report\n`;
    report += `Period: ${period}\n`;
    report += `Date Range: ${dateRange}\n\n`;
    report += `═══════════════════════════\n\n`;
    report += `📈 Summary\n`;
    report += `Total Consumption: ${totalKwh.toFixed(1)} kWh\n`;
    report += `Total Cost: ₱${totalCost.toFixed(2)}\n\n`;
    report += `═══════════════════════════\n\n`;
    report += `🔌 Appliance Breakdown\n\n`;
    
    appliances.forEach((appliance, index) => {
      report += `${index + 1}. ${appliance.name}\n`;
      report += `   ${appliance.kwh.toFixed(1)} kWh | ₱${appliance.cost.toFixed(2)}\n\n`;
    });
    
    report += `═══════════════════════════\n`;
    report += `Generated by NILM App\n`;
    report += `${new Date().toLocaleString()}\n`;
    
    return report;
  };

  const generateCSV = (): string => {
    const { appliances } = reportData;
    
    let csv = 'Appliance,Consumption (kWh),Cost (PHP)\n';
    appliances.forEach(appliance => {
      csv += `${appliance.name},${appliance.kwh.toFixed(2)},${appliance.cost.toFixed(2)}\n`;
    });
    
    return csv;
  };

  const handleShareText = async () => {
    try {
      const text = generateTextReport();
      await Share.share({
        message: text,
        title: 'Energy Consumption Report',
      });
      onClose();
    } catch (error) {
      console.error('Error sharing:', error);
      Alert.alert('Error', 'Failed to share report');
    }
  };

  const handleCopyToClipboard = async () => {
    try {
      const text = generateTextReport();
      await Clipboard.setStringAsync(text);
      Alert.alert(
        'Copied!',
        'Report data has been copied to clipboard',
        [{ text: 'OK', onPress: onClose }]
      );
    } catch (error) {
      console.error('Error copying to clipboard:', error);
      Alert.alert('Error', 'Failed to copy to clipboard');
    }
  };

  const handleExportCSV = async () => {
    try {
      const csv = generateCSV();
      const { period, dateRange } = reportData;
      
      // Generate filename
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `energy-report-${period}-${timestamp}.csv`;
      const fileUri = `${FileSystem.cacheDirectory}${filename}`;

      // Write CSV to file
      await FileSystem.writeAsStringAsync(fileUri, csv);

      // Check if sharing is available
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/csv',
          dialogTitle: 'Export Energy Report',
          UTI: 'public.comma-separated-values-text',
        });
        onClose();
      } else {
        // Fallback to native share
        await Share.share({
          message: csv,
          title: 'Energy Report CSV',
        });
        onClose();
      }
    } catch (error) {
      console.error('Error exporting CSV:', error);
      Alert.alert('Error', 'Failed to export CSV. Please try sharing as text instead.');
    }
  };

  const generateHTMLReport = (): string => {
    const { period, dateRange, totalKwh, totalCost, appliances } = reportData;
    const bgColor = isDark ? '#1C1C1E' : '#FFFFFF';
    const textColor = isDark ? '#FFFFFF' : '#000000';
    const secondaryColor = isDark ? '#8E8E93' : '#6C757D';
    const cardBg = isDark ? '#2C2C2E' : '#F8F9FA';
    
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            background: ${bgColor};
            color: ${textColor};
            padding: 40px 20px;
            line-height: 1.6;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #007AFF;
            padding-bottom: 20px;
          }
          .header h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 10px;
            color: #007AFF;
          }
          .header p {
            font-size: 14px;
            color: ${secondaryColor};
            margin-bottom: 5px;
          }
          .summary {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 30px;
          }
          .summary-card {
            background: ${cardBg};
            padding: 20px;
            border-radius: 12px;
            text-align: center;
            border: 1px solid ${isDark ? '#3A3A3C' : '#E9ECEF'};
          }
          .summary-label {
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: ${secondaryColor};
            margin-bottom: 8px;
            font-weight: 600;
          }
          .summary-value {
            font-size: 32px;
            font-weight: 700;
            color: #007AFF;
          }
          .section-title {
            font-size: 20px;
            font-weight: 700;
            margin: 30px 0 15px;
            color: ${textColor};
            border-left: 4px solid #007AFF;
            padding-left: 12px;
          }
          .appliance-table {
            width: 100%;
            border-collapse: collapse;
            background: ${cardBg};
            border-radius: 12px;
            overflow: hidden;
            border: 1px solid ${isDark ? '#3A3A3C' : '#E9ECEF'};
          }
          .appliance-table thead {
            background: #007AFF;
            color: white;
          }
          .appliance-table th,
          .appliance-table td {
            padding: 12px 16px;
            text-align: left;
            border-bottom: 1px solid ${isDark ? '#3A3A3C' : '#E9ECEF'};
          }
          .appliance-table th {
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .appliance-table tr:last-child td {
            border-bottom: none;
          }
          .appliance-table tbody tr:hover {
            background: ${isDark ? '#3A3A3C' : '#F1F3F5'};
          }
          .text-right {
            text-align: right;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid ${isDark ? '#3A3A3C' : '#E9ECEF'};
            text-align: center;
            color: ${secondaryColor};
            font-size: 12px;
          }
          .cost-value {
            color: #34C759;
            font-weight: 600;
          }
          @media print {
            body { padding: 20px; }
            .summary { page-break-inside: avoid; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>⚡ Energy Consumption Report</h1>
          <p><strong>Period:</strong> ${period}</p>
          <p><strong>Date Range:</strong> ${dateRange}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        </div>

        <div class="summary">
          <div class="summary-card">
            <div class="summary-label">Total Consumption</div>
            <div class="summary-value">${totalKwh.toFixed(1)} <span style="font-size: 18px;">kWh</span></div>
          </div>
          <div class="summary-card">
            <div class="summary-label">Total Cost</div>
            <div class="summary-value cost-value">₱${totalCost.toFixed(2)}</div>
          </div>
        </div>

        <h2 class="section-title">🔌 Appliance Breakdown</h2>
        <table class="appliance-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Appliance</th>
              <th class="text-right">Consumption</th>
              <th class="text-right">Cost</th>
            </tr>
          </thead>
          <tbody>
            ${appliances.map((appliance, index) => `
              <tr>
                <td>${index + 1}</td>
                <td><strong>${appliance.name}</strong></td>
                <td class="text-right">${appliance.kwh.toFixed(1)} kWh</td>
                <td class="text-right cost-value">₱${appliance.cost.toFixed(2)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          <p><strong>Generated by NILM App</strong></p>
          <p>Non-Intrusive Load Monitoring System</p>
          <p>For assistance, contact your system administrator</p>
        </div>
      </body>
      </html>
    `;
  };

  const handleExportPDF = async () => {
    try {
      setIsExporting(true);
      const html = generateHTMLReport();
      const { period, dateRange } = reportData;
      
      // Generate filename
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `energy-report-${period}-${timestamp}.pdf`;

      // Create PDF
      const { uri } = await Print.printToFileAsync({
        html,
        base64: false,
      });

      // Share the PDF
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Export Energy Report',
          UTI: 'com.adobe.pdf',
        });
        onClose();
      } else {
        Alert.alert(
          'PDF Created',
          'PDF has been created successfully. Check your downloads folder.',
          [{ text: 'OK', onPress: onClose }]
        );
      }
    } catch (error) {
      console.error('Error exporting PDF:', error);
      Alert.alert('Error', 'Failed to export PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={onClose}>
      <TouchableOpacity
        style={styles.overlay}
        activeOpacity={1}
        onPress={onClose}>
        <View style={styles.container}>
          <View style={styles.header}>
            <Text style={styles.title}>Export Report</Text>
          </View>

          <View style={styles.options}>
            <TouchableOpacity style={styles.option} onPress={handleShareText}>
              <Text style={styles.optionIcon}>📤</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Share Report</Text>
                <Text style={styles.optionDescription}>
                  Share via messaging apps, email, etc.
                </Text>
              </View>
              <Text style={styles.optionArrow}>→</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.option} onPress={handleCopyToClipboard}>
              <Text style={styles.optionIcon}>📋</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Copy to Clipboard</Text>
                <Text style={styles.optionDescription}>
                  Copy report data as text
                </Text>
              </View>
              <Text style={styles.optionArrow}>→</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.option} onPress={handleExportCSV}>
              <Text style={styles.optionIcon}>📊</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Export as CSV</Text>
                <Text style={styles.optionDescription}>
                  Download data for Excel/Sheets
                </Text>
              </View>
              <Text style={styles.optionArrow}>→</Text>
            </TouchableOpacity>

            <TouchableOpacity 
              style={[styles.option, isExporting && styles.optionDisabled]} 
              onPress={handleExportPDF}
              disabled={isExporting}>
              <Text style={styles.optionIcon}>📄</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Export as PDF</Text>
                <Text style={styles.optionDescription}>
                  {isExporting ? 'Generating PDF...' : 'Generate printable report'}
                </Text>
              </View>
              {isExporting ? (
                <ActivityIndicator size="small" color={colors.primary} />
              ) : (
                <Text style={styles.optionArrow}>→</Text>
              )}
            </TouchableOpacity>
          </View>

          <TouchableOpacity style={styles.cancelButton} onPress={onClose}>
            <Text style={styles.cancelButtonText}>Cancel</Text>
          </TouchableOpacity>
        </View>
      </TouchableOpacity>
    </Modal>
  );
}

const createStyles = (colors: any) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    container: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      width: '100%',
      maxWidth: 400,
      overflow: 'hidden',
    },
    header: {
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    title: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    options: {
      padding: 12,
    },
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      backgroundColor: colors.background,
    },
    optionIcon: {
      fontSize: 24,
      marginRight: 12,
    },
    optionContent: {
      flex: 1,
    },
    optionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textPrimary,
      marginBottom: 2,
    },
    optionDescription: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    optionArrow: {
      fontSize: 20,
      color: colors.textSecondary,
      marginLeft: 12,
    },
    optionBadge: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.warning,
      backgroundColor: `${colors.warning}20`,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
      marginLeft: 12,
    },
    optionDisabled: {
      opacity: 0.5,
    },
    cancelButton: {
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.divider,
      alignItems: 'center',
    },
    cancelButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textSecondary,
    },
  });
