/**
 * Export Menu Component
 * Provides options to share and export report data
 */

import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, Alert, Share, Platform } from 'react-native';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import * as Clipboard from 'expo-clipboard';
import { useTheme } from '@/contexts/ThemeContext';

interface ExportMenuProps {
  visible: boolean;
  onClose: () => void;
  reportData: {
    period: string;
    dateRange: string;
    totalKwh: number;
    totalCost: number;
    appliances: Array<{
      name: string;
      kwh: number;
      cost: number;
    }>;
  };
}

export function ExportMenu({ visible, onClose, reportData }: ExportMenuProps) {
  const { colors } = useTheme();
  const styles = createStyles(colors);

  const generateTextReport = (): string => {
    const { period, dateRange, totalKwh, totalCost, appliances } = reportData;
    
    let report = `📊 Energy Consumption Report\n`;
    report += `Period: ${period}\n`;
    report += `Date Range: ${dateRange}\n\n`;
    report += `═══════════════════════════\n\n`;
    report += `📈 Summary\n`;
    report += `Total Consumption: ${totalKwh.toFixed(1)} kWh\n`;
    report += `Total Cost: ₱${totalCost.toFixed(2)}\n\n`;
    report += `═══════════════════════════\n\n`;
    report += `🔌 Appliance Breakdown\n\n`;
    
    appliances.forEach((appliance, index) => {
      report += `${index + 1}. ${appliance.name}\n`;
      report += `   ${appliance.kwh.toFixed(1)} kWh | ₱${appliance.cost.toFixed(2)}\n\n`;
    });
    
    report += `═══════════════════════════\n`;
    report += `Generated by NILM App\n`;
    report += `${new Date().toLocaleString()}\n`;
    
    return report;
  };

  const generateCSV = (): string => {
    const { appliances } = reportData;
    
    let csv = 'Appliance,Consumption (kWh),Cost (PHP)\n';
    appliances.forEach(appliance => {
      csv += `${appliance.name},${appliance.kwh.toFixed(2)},${appliance.cost.toFixed(2)}\n`;
    });
    
    return csv;
  };

  const handleShareText = async () => {
    try {
      const text = generateTextReport();
      await Share.share({
        message: text,
        title: 'Energy Consumption Report',
      });
      onClose();
    } catch (error) {
      console.error('Error sharing:', error);
      Alert.alert('Error', 'Failed to share report');
    }
  };

  const handleCopyToClipboard = async () => {
    try {
      const text = generateTextReport();
      await Clipboard.setStringAsync(text);
      Alert.alert(
        'Copied!',
        'Report data has been copied to clipboard',
        [{ text: 'OK', onPress: onClose }]
      );
    } catch (error) {
      console.error('Error copying to clipboard:', error);
      Alert.alert('Error', 'Failed to copy to clipboard');
    }
  };

  const handleExportCSV = async () => {
    try {
      const csv = generateCSV();
      const { period, dateRange } = reportData;
      
      // Generate filename
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `energy-report-${period}-${timestamp}.csv`;
      const fileUri = `${FileSystem.cacheDirectory}${filename}`;

      // Write CSV to file
      await FileSystem.writeAsStringAsync(fileUri, csv);

      // Check if sharing is available
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/csv',
          dialogTitle: 'Export Energy Report',
          UTI: 'public.comma-separated-values-text',
        });
        onClose();
      } else {
        // Fallback to native share
        await Share.share({
          message: csv,
          title: 'Energy Report CSV',
        });
        onClose();
      }
    } catch (error) {
      console.error('Error exporting CSV:', error);
      Alert.alert('Error', 'Failed to export CSV. Please try sharing as text instead.');
    }
  };

  const handleExportPDF = () => {
    Alert.alert(
      'PDF Export',
      'PDF export will be available in the next update. For now, you can share as text or take a screenshot.',
      [
        { text: 'OK', style: 'cancel' },
        { text: 'Share as Text', onPress: handleShareText },
      ]
    );
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={onClose}>
      <TouchableOpacity
        style={styles.overlay}
        activeOpacity={1}
        onPress={onClose}>
        <View style={styles.container}>
          <View style={styles.header}>
            <Text style={styles.title}>Export Report</Text>
          </View>

          <View style={styles.options}>
            <TouchableOpacity style={styles.option} onPress={handleShareText}>
              <Text style={styles.optionIcon}>📤</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Share Report</Text>
                <Text style={styles.optionDescription}>
                  Share via messaging apps, email, etc.
                </Text>
              </View>
              <Text style={styles.optionArrow}>→</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.option} onPress={handleCopyToClipboard}>
              <Text style={styles.optionIcon}>📋</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Copy to Clipboard</Text>
                <Text style={styles.optionDescription}>
                  Copy report data as text
                </Text>
              </View>
              <Text style={styles.optionArrow}>→</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.option} onPress={handleExportCSV}>
              <Text style={styles.optionIcon}>📊</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Export as CSV</Text>
                <Text style={styles.optionDescription}>
                  Download data for Excel/Sheets
                </Text>
              </View>
              <Text style={styles.optionArrow}>→</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.option} onPress={handleExportPDF}>
              <Text style={styles.optionIcon}>📄</Text>
              <View style={styles.optionContent}>
                <Text style={styles.optionTitle}>Export as PDF</Text>
                <Text style={styles.optionDescription}>
                  Generate printable report
                </Text>
              </View>
              <Text style={styles.optionBadge}>Coming Soon</Text>
            </TouchableOpacity>
          </View>

          <TouchableOpacity style={styles.cancelButton} onPress={onClose}>
            <Text style={styles.cancelButtonText}>Cancel</Text>
          </TouchableOpacity>
        </View>
      </TouchableOpacity>
    </Modal>
  );
}

const createStyles = (colors: any) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    container: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      width: '100%',
      maxWidth: 400,
      overflow: 'hidden',
    },
    header: {
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    title: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    options: {
      padding: 12,
    },
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      backgroundColor: colors.background,
    },
    optionIcon: {
      fontSize: 24,
      marginRight: 12,
    },
    optionContent: {
      flex: 1,
    },
    optionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textPrimary,
      marginBottom: 2,
    },
    optionDescription: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    optionArrow: {
      fontSize: 20,
      color: colors.textSecondary,
      marginLeft: 12,
    },
    optionBadge: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.warning,
      backgroundColor: `${colors.warning}20`,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
      marginLeft: 12,
    },
    cancelButton: {
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.divider,
      alignItems: 'center',
    },
    cancelButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textSecondary,
    },
  });
